"""generate chat models

Revision ID: 0371afa4fbf0
Revises: 883990c30c41
Create Date: 2024-08-28 21:19:42.206514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "0371afa4fbf0"
down_revision: Union[str, None] = "883990c30c41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Enum for 'asset_contents.processing' column
assetprocessingstatus = sa.Enum(
    "IN_PROGRESS", "COMPLETED", name="assetprocessingstatus"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column(
            "id", sa.String(length=36), nullable=False
        ),  # Use String for UUID in SQLite
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_id"), "conversations", ["id"], unique=False)

    op.create_table(
        "conversation_messages",
        sa.Column(
            "id", sa.String(length=36), nullable=False
        ),  # Use String for UUID in SQLite
        sa.Column(
            "conversation_id", sa.String(length=36), nullable=False
        ),  # Match the type used in conversations
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_messages_id"),
        "conversation_messages",
        ["id"],
        unique=False,
    )

    # Adding the 'processing' column to 'asset_contents'
    op.add_column(
        "asset_contents", sa.Column("processing", assetprocessingstatus, nullable=False)
    )

    # SQLite does not support altering column types, so handle it by recreating the table
    # Step 1: Rename the existing table
    op.rename_table("asset_contents", "asset_contents_old")

    # Step 2: Create a new table with the modified structure
    op.create_table(
        "asset_contents",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=True),  # Changed to nullable=True
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "language", sa.String(length=10), nullable=True, server_default="en"
        ),  # Changed to nullable=True
        sa.Column("processing", assetprocessingstatus, nullable=False),  # New column
    )

    # Step 3: Copy data from the old table to the new table
    op.execute(
        """
        INSERT INTO asset_contents (id, asset_id, content, language, processing)
        SELECT id, asset_id, content, language, 'IN_PROGRESS' FROM asset_contents_old
    """
    )

    # Step 4: Drop the old table
    op.drop_table("asset_contents_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the changes made in the upgrade

    # Drop the 'processing' column
    op.drop_column("asset_contents", "processing")

    # Rename the table back to the old name
    op.rename_table("asset_contents", "asset_contents_new")

    # Recreate the old table structure
    op.create_table(
        "asset_contents",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),  # Reverted to nullable=False
        sa.Column(
            "language", sa.String(length=10), nullable=False, server_default="en"
        ),  # Reverted to nullable=False
    )

    # Copy data back from the new table to the old structure
    op.execute(
        """
        INSERT INTO asset_contents (id, asset_id, content, language)
        SELECT id, asset_id, content, language FROM asset_contents_new
    """
    )

    # Drop the temporary new table
    op.drop_table("asset_contents_new")

    # Drop conversation messages table
    op.drop_index(
        op.f("ix_conversation_messages_id"), table_name="conversation_messages"
    )
    op.drop_table("conversation_messages")

    # Drop conversations table
    op.drop_index(op.f("ix_conversations_id"), table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
