"""soft deleted columns added

Revision ID: 1df766359982
Revises: ccfafd40eaf9
Create Date: 2024-07-24 17:13:34.848313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df766359982'
down_revision: Union[str, None] = 'ccfafd40eaf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('assets', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'deleted')
    op.drop_column('assets', 'deleted_at')
    op.drop_column('assets', 'deleted')
    # ### end Alembic commands ###
