"""rename_column_summary

Revision ID: 1f99c0166797
Revises: 92f4fabcce75
Create Date: 2024-07-25 11:34:21.648424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1f99c0166797'
down_revision: Union[str, None] = '92f4fabcce75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processes', sa.Column('output', sa.JSON(), nullable=True))
    op.drop_column('processes', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processes', sa.Column('summary', sqlite.JSON(), nullable=True))
    op.drop_column('processes', 'output')
    # ### end Alembic commands ###
