"""process_add_summary

Revision ID: 2484b46ee17d
Revises: ccfafd40eaf9
Create Date: 2024-07-24 17:19:46.186173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2484b46ee17d'
down_revision: Union[str, None] = 'ccfafd40eaf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processes', sa.Column('summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processes', 'summary')
    # ### end Alembic commands ###
