"""add_process_step_status

Revision ID: 284ed84c1933
Revises: e1e475154dfc
Create Date: 2024-07-22 12:54:19.905121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "284ed84c1933"
down_revision: Union[str, None] = "e1e475154dfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "process_steps",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                name="processstepstatus",
            ),
            nullable=False,
            server_default="PENDING",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("process_steps", "status")
    # ### end Alembic commands ###
