"""store_asset_content

Revision ID: 52638004c665
Revises: ca718b243f47
Create Date: 2024-07-30 14:22:19.648805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52638004c665'
down_revision: Union[str, None] = 'ca718b243f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_contents_asset_id'), 'asset_contents', ['asset_id'], unique=True)
    op.create_index(op.f('ix_asset_contents_id'), 'asset_contents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_contents_id'), table_name='asset_contents')
    op.drop_index(op.f('ix_asset_contents_asset_id'), table_name='asset_contents')
    op.drop_table('asset_contents')
    # ### end Alembic commands ###
