"""add asset size

Revision ID: 86611d367b4e
Revises: 0371afa4fbf0
Create Date: 2024-09-06 12:02:36.869292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86611d367b4e"
down_revision: Union[str, None] = "0371afa4fbf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assets", sa.Column("size", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "size")
    # ### end Alembic commands ###
