"""update asset type and add metadata

Revision ID: 883990c30c41
Revises: 1aea8dc0bfda
Create Date: 2024-08-14 13:17:23.130375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "883990c30c41"
down_revision: Union[str, None] = "1aea8dc0bfda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assets", sa.Column("type", sa.String(length=255), nullable=False))
    op.add_column("assets", sa.Column("details", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "details")
    op.drop_column("assets", "type")
    # ### end Alembic commands ###
