"""Add datetimes to all tables

Revision ID: 917de9c35f18
Revises: 1f99c0166797
Create Date: 2024-07-28 11:31:07.905073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917de9c35f18'
down_revision: Union[str, None] = '1f99c0166797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('api_keys', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('assets', 'deleted')
    op.add_column('process_steps', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('processes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('projects', 'deleted')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.add_column('projects', sa.Column('deleted', sa.BOOLEAN(), nullable=True))
    op.drop_column('processes', 'deleted_at')
    op.drop_column('process_steps', 'deleted_at')
    op.add_column('assets', sa.Column('deleted', sa.BOOLEAN(), nullable=True))
    op.drop_column('api_keys', 'deleted_at')
    op.drop_column('api_keys', 'updated_at')
    # ### end Alembic commands ###
