"""Add name to the process

Revision ID: ca718b243f47
Revises: 917de9c35f18
Create Date: 2024-07-29 15:29:19.433665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca718b243f47'
down_revision: Union[str, None] = '917de9c35f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processes', sa.Column('name', sa.String(length=255), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processes', 'name')
    # ### end Alembic commands ###
