"""add_process_step

Revision ID: e1e475154dfc
Revises: 34b7216ce425
Create Date: 2024-07-19 17:31:33.232000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e475154dfc'
down_revision: Union[str, None] = '34b7216ce425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_steps_id'), 'process_steps', ['id'], unique=False)
    op.add_column('processes', sa.Column('details', sa.JSON(), nullable=True))
    op.add_column('processes', sa.Column('message', sa.String(length=255), nullable=False))
    op.alter_column('processes', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processes', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processstatus'),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('processes', 'message')
    op.drop_column('processes', 'details')
    op.drop_index(op.f('ix_process_steps_id'), table_name='process_steps')
    op.drop_table('process_steps')
    # ### end Alembic commands ###
